version: '3'

services:
  web:
    build: .
    image: lambdaway
    restart: always
    ports:
      - 80:80
    volumes:
      - "lambdaway_data:/var/www/html/data"
      - "lambdaway_pages:/var/www/html/pages"
      - "lambdaway_history:/var/www/html/history"
      
      # for DEBUG only:
      - "./meca:/var/www/html/meca"
      - "./.htaccess:/var/www/html/.htaccess"

volumes:
  lambdaway_data:
  lambdaway_pages:
  lambdaway_history:
